spring:
  application:
    name: branch-holidays-api
  mongodb:
    uri: mongodb+srv://admin:admin@cluster0.fgl4sfn.mongodb.net/branchdb?retryWrites=true&w=majority

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs